In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]


In [3]:
voc_size=10000

In [4]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[9005, 9235, 434, 7185], [9005, 9235, 434, 1591], [9005, 2548, 434, 8905], [1899, 6201, 6604, 4856, 184], [1899, 6201, 6604, 4856, 9513], [4209, 9005, 4625, 434, 7351], [4635, 2408, 1364, 4856]]


In [5]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9005 9235  434 7185]
 [   0    0    0    0 9005 9235  434 1591]
 [   0    0    0    0 9005 2548  434 8905]
 [   0    0    0 1899 6201 6604 4856  184]
 [   0    0    0 1899 6201 6604 4856 9513]
 [   0    0    0 4209 9005 4625  434 7351]
 [   0    0    0    0 4635 2408 1364 4856]]


In [10]:
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
print(model.predict(embedded_docs))

[[[-4.52088192e-03  7.87050650e-03  1.08276010e-02 -1.43981948e-02
   -4.76483591e-02 -4.87609282e-02 -3.05866953e-02 -2.63428092e-02
   -1.67288408e-02  3.02238502e-02]
  [-4.52088192e-03  7.87050650e-03  1.08276010e-02 -1.43981948e-02
   -4.76483591e-02 -4.87609282e-02 -3.05866953e-02 -2.63428092e-02
   -1.67288408e-02  3.02238502e-02]
  [-4.52088192e-03  7.87050650e-03  1.08276010e-02 -1.43981948e-02
   -4.76483591e-02 -4.87609282e-02 -3.05866953e-02 -2.63428092e-02
   -1.67288408e-02  3.02238502e-02]
  [-4.52088192e-03  7.87050650e-03  1.08276010e-02 -1.43981948e-02
   -4.76483591e-02 -4.87609282e-02 -3.05866953e-02 -2.63428092e-02
   -1.67288408e-02  3.02238502e-02]
  [ 8.24570656e-03  2.02228762e-02  1.18654966e-03 -2.26709489e-02
    4.42767628e-02  4.98367436e-02  2.79762633e-02 -3.00981887e-02
   -4.73608039e-02  4.18553017e-02]
  [ 4.66939323e-02 -3.28613408e-02  1.64939426e-02 -8.81876796e-03
   -2.22591516e-02  4.09667827e-02  4.17616852e-02  3.80651094e-02
   -2.74351370e-